[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "meilisearch"
description = "The python client for Meilisearch API."
license = { text = "MIT" }
requires-python = ">=3.7"
authors = [
  { name = "Charlotte Vermandel", email = "charlotte@meilisearch.com" },
]
keywords = [
  "search",
  "python",
  "meilisearch",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests",
    "camel-converter[pydantic]",
]
dynamic = ['version']

[tool.setuptools.dynamic]
version = {attr = "meilisearch.version.__version__"}

[project.urls]
Meilisearch_Documentation = "https://docs.meilisearch.com/"
Documentation = "https://meilisearch.github.io/meilisearch-python/"
Homepage = "https://github.com/meilisearch/meilisearch-python"

[tool.black]
line-length = 100
target-version = ['py37']
include = '\.pyi?$'
extend-exclude = '''
/(
    \.egg
  | \.git
  | \.hg
  | \.mypy_cache
  | \.nox
  | \.tox
  | \.venv
  | \venv
  | _build
  | buck-out
  | build
  | dist
  | setup.py
)/
'''

[tool.isort]
profile = "black"
line_length = 100
src_paths = ["meilisearch", "tests", "setup.py"]

[tool.mypy]
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = ["tests.*"]
disallow_untyped_defs = false

[tool.pylint.basic]
bad-functions=[
  "map",
  "filter",
  "input"
]
fconst-rgx = "(([A-Z_][A-Z0-9_]*)|(__.*__))$"
const-name-hint = "(([A-Z_][A-Z0-9_]*)|(__.*__))$"
attr-rgx = "[a-z_][a-z0-9_]{2,}$"
attr-name-hint = "[a-z_][a-z0-9_]{2,}$"
module-rgx = "(([a-z_][a-z0-9_]*)|([A-Z][a-zA-Z0-9]+))$"
module-name-hint = "(([a-z_][a-z0-9_]*)|([A-Z][a-zA-Z0-9]+))$"
method-rgx = "[a-z_][a-z0-9_]{2,}$"
method-name-hint = "[a-z_][a-z0-9_]{2,}$"

[tool.pylint.design]
max-args = 10
max-public-methods = 25

[tool.pylint.format]
max-module-lines=2000
no-space-check=[
  "trailing-comma",
  "dict-separator"
]

[tool.pylint.messages_control]
enable=[
  "use-symbolic-message-instead",
  "useless-supression",
  "fixme",
]

[tool.pylint.report]
files-output = "no"
